### ISSUE TITLE
cant type in password.

### ISSUE THREAD

**Issue by Necessarycoot72** [Footsiefat/zspotify#168]
So I install zspoify using the scoop method, and when prompted, I can't type anything in the password field. Not even ctrl-v does anything. When I press enter, still on the password field, I get this.

Traceback (most recent call last):
  File "C:\Users\[USER]\scoop\apps\python\current\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\[USER]\scoop\apps\python\current\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\[USER]\Downloads\zspotify\zspotify\zspotify\__main__.py", line 4, in <module>
    client()
  File "C:\Users\[USER]\Downloads\zspotify\zspotify\zspotify\app.py", line 20, in client
    ZSpotify()
  File "C:\Users\[USER]\Downloads\zspotify\zspotify\zspotify\zspotify.py", line 32, in __init__
    ZSpotify.login()
  File "C:\Users\[USER]\Downloads\zspotify\zspotify\zspotify\zspotify.py", line 50, in login
    cls.SESSION = Session.Builder().user_pass(user_name, password).create()
  File "C:\Users\[USER]\scoop\apps\python\current\lib\site-packages\librespot\core.py", line 1224, in create
    session.authenticate(self.login_credentials)
  File "C:\Users\[USER]\scoop\apps\python\current\lib\site-packages\librespot\core.py", line 650, in authenticate
    self.__authenticate_partial(credential, False)
  File "C:\Users\[USER]\scoop\apps\python\current\lib\site-packages\librespot\core.py", line 1007, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.SpotifyAuthenticationException: BadCredentials
PS C:\Users\[USER]\Downloads\zspotify\zspotify>

I censored my name for privacy.

If it helps I use a 64bit version of windows.

**Comment by Necessarycoot72** [comment]
> some special characters are known problems for the spotlibre client try changing your password
I'm not using any special characters.
 
> You're not supposed to be able to see your password when you type it in, if that's what your confused about
when I type there are no characters showing up at all.

**Comment by Necessarycoot72** [comment]
fixed. for some reason you cant paste passwords.
