### ISSUE TITLE
[BUG] keyerror on pulling a playlist

### ISSUE THREAD

**Issue by ElianaTroper** [Footsiefat/zspotify#194]
**Describe the bug**
Try running `python zspotify PLAYLIST_URL`. Output is:

```Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/troper/Apps/zspotify/zspotify/__main__.py", line 38, in <module>
    args.func(args)
  File "/home/troper/Apps/zspotify/zspotify/app.py", line 46, in client
    download_from_urls(args.urls)
  File "/home/troper/Apps/zspotify/zspotify/app.py", line 87, in download_from_urls
    playlist_songs = get_playlist_songs(playlist_id)
  File "/home/troper/Apps/zspotify/zspotify/playlist.py", line 37, in get_playlist_songs
    songs.extend(resp[ITEMS])
KeyError: 'items'
```

**To Reproduce**
1. Enter `python zspotify PLAYLIST_URL`
3. See error

**Expected behavior**
Start downloading a playlist.

**Screenshots**

**System Info:**
 - OS: Ubuntu 20.04
 - Release: source (latest at time of this comment)

**Comment by ElianaTroper** [comment]
Oof, turns out playlist was private and account did not have access.
