### ISSUE TITLE
traceback error 

### ISSUE THREAD

**Issue by cooper7692** [Footsiefat/zspotify#212]
Traceback (most recent call last):
  File "C:\Users\coope\Desktop\ZSpotify\Source\zspotify\track.py", line 119, in download_track
    c = len([file for file in os.listdir(filedir) if re.search(f'^{filename}_', str(file))]) + 1
  File "C:\Users\coope\Desktop\ZSpotify\Source\zspotify\track.py", line 119, in <listcomp>
    c = len([file for file in os.listdir(filedir) if re.search(f'^{filename}_', str(file))]) + 1
  File "C:\Users\coope\AppData\Local\Programs\Python\Python310\lib\re.py", line 200, in search
    return _compile(pattern, flags).search(string)
  File "C:\Users\coope\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\coope\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\coope\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\coope\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\coope\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 525, in _parse
    code = _escape(source, this, state)
  File "C:\Users\coope\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 381, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 3

**Comment by leonbohmann** [comment]
What did you define in your zs_config? This seems like an error because of some file path?

**Comment by cooper7692** [comment]
was default lol, only happened on certain downloads.
