### ISSUE TITLE
[BUG] TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by CyberLykan** [Footsiefat/zspotify#213]
**Describe the bug**
Using the Windows Installer version, `TypeError: 'type' object is not subscriptable` is returned upon start.

**To Reproduce**
1. Install only zspotify from the installer. (Python and Git are installed already.)
2. Run zspotify.

**Expected behavior**
Launch to main menu.

**System Info:**
 - OS: Windows 10
 - Release: exe
 - Version: Windows Installer v1.0

**Additional context**
```
C:\Users\johndoe>C:\Users\Public\Desktop\ZSpotify.lnk

D:\My Stuff\Extra Stuff\zspotify\Source>call ZSpot-env\Scripts\activate.bat
Traceback (most recent call last):
  File "C:\Users\johndoe\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\johndoe\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\My Stuff\Extra Stuff\zspotify\Source\zspotify\__main__.py", line 3, in <module>
    from app import client
  File "D:\My Stuff\Extra Stuff\zspotify\Source\zspotify\app.py", line 64, in <module>
    def download_from_urls(urls: list[str]) -> bool:
TypeError: 'type' object is not subscriptable
```

**Comment by seanawesome** [comment]
I am getting the same error message.

**Comment by logykk** [comment]
Caused by using an outdated python version. Python 3.8 is unsupported and breaks zspotify, you'll need to upgrade to 3.9 or greater.
