### ISSUE TITLE
[BUG] API limit exceeded after downloading ~5000 songs

### ISSUE THREAD

**Issue by eneller** [Footsiefat/zspotify#221]
After downloading approx. 5300 songs in one siting, i get an "API limit exceeded" error.

**System Info:**
 - OS: raspberry pi os
 - Release: source

Error message after trying to restart is this (didnt copy the original error)
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/zspotify/zspotify/__main__.py", line 46, in <module>
    args.func(args)
  File "/home/pi/zspotify/zspotify/app.py", line 44, in client
    download_from_urls(args.urls)
  File "/home/pi/zspotify/zspotify/app.py", line 83, in download_from_urls
    playlist_songs = get_playlist_songs(playlist_id)
  File "/home/pi/zspotify/zspotify/playlist.py", line 36, in get_playlist_songs
    songs.extend(resp[ITEMS])
KeyError: 'items'
```

**Comment by cooper7692** [comment]
uh, its probably got a time limiter on it of some sort. every 4 hours or something like that, are you still having this problem?

**Comment by eneller** [comment]
no i dont, i thought the same and just waited until i restarted it
