### ISSUE TITLE
[BUG] UnboundLocalError: local variable 'prepareDownloadLoader' referenced before assignment

### ISSUE THREAD

**Issue by TrevorBarns** [Footsiefat/zspotify#229]
**Describe the bug**
Crash on `python zspotify -ls` with multiple traces each time referring to prepareDownloadLoader and Printer has no attribute Print.
**To Reproduce**

1. Enter `python zspotify -ls`
2. Enter '....' (occurs while skipping existing files and fails to query metadata)
3. See error 

**Expected behavior**
It not to crash and continue without that tracks metadata.

**Screenshots**

**System Info:**
 - OS: Windows 10 
 - Release: Latest Window Binary
 - Version: v0.5.1.2

**Additional context**
```
###   SKIPPING SONG - FAILED TO QUERY METADATA   ###
Track_ID: XXXXXXXXXXXXXXXXXXXX

type object 'Printer' has no attribute 'Print'

Traceback (most recent call last):
  File "D:\Computer\Desktop\ZSpotify\zspotify\track.py", line 104, in download_track
    track_number, scraped_song_id, is_playable, duration_ms) = get_song_info(track_id)
  File "D:\Computer\Desktop\ZSpotify\zspotify\track.py", line 42, in get_song_info
    (raw, info) = ZSpotify.invoke_url(f'{TRACKS_URL}?ids={song_id}&market=from_token')
  File "D:\Computer\Desktop\ZSpotify\zspotify\zspotify.py", line 94, in invoke_url
    Printer.Print(PrintChannel.API_ERROR, f"Spotify API Error ({responseJson['error']['status']}): {responseJson['error']['message']}")
AttributeError: type object 'Printer' has no attribute 'Print'


Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Computer\Desktop\ZSpotify\zspotify\__main__.py", line 46, in <module>
    args.func(args)
  File "D:\Computer\Desktop\ZSpotify\zspotify\app.py", line 54, in client
    download_track('liked', song[TRACK][ID])
  File "D:\Computer\Desktop\ZSpotify\zspotify\track.py", line 226, in download_track
    prepareDownloadLoader.stop()
UnboundLocalError: local variable 'prepareDownloadLoader' referenced before assignment
```

**Comment by TrevorBarns** [comment]
Without looking too far into I solved the problem by removing: 
https://github.com/Footsiefat/zspotify/blob/d37ab438801d06efd208cf999fb34958eadc5f54/zspotify/track.py#L226

Which appears to run after prepareDownloadLoader.stop(); is stopped in error catching.

**Comment by TotallyNotInUse** [comment]
I'm getting the same issue, I don't know if it's related to your issue:

```
###   SKIPPING SONG - FAILED TO QUERY METADATA   ###
Track_ID: None

Failed to parse TRACKS_URL response: 'NoneType' object is not subscriptable
{
  "tracks" : [ null ]
}

Traceback (most recent call last):
  File "C:\Users\User\Desktop\zspotify-main\zspotify\track.py", line 50, in get_song_info
    for data in info[TRACKS][0][ARTISTS]:
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\zspotify-main\zspotify\track.py", line 104, in download_track
    track_number, scraped_song_id, is_playable, duration_ms) = get_song_info(track_id)
  File "C:\Users\User\Desktop\zspotify-main\zspotify\track.py", line 77, in get_song_info
    raise ValueError(f'Failed to parse TRACKS_URL response: {str(e)}\n{raw}')
ValueError: Failed to parse TRACKS_URL response: 'NoneType' object is not subscriptable
{
  "tracks" : [ null ]
}


Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Desktop\zspotify-main\zspotify\__main__.py", line 46, in <module>
    args.func(args)
  File "C:\Users\User\Desktop\zspotify-main\zspotify\app.py", line 44, in client
    download_from_urls(args.urls)
  File "C:\Users\User\Desktop\zspotify-main\zspotify\app.py", line 91, in download_from_urls
    download_track('playlist', song[TRACK][ID], extra_keys={'playlist': name, 'playlist_num': str(enum).zfill(char_num)})
  File "C:\Users\User\Desktop\zspotify-main\zspotify\track.py", line 226, in download_track
    prepareDownloadLoader.stop()
UnboundLocalError: local variable 'prepareDownloadLoader' referenced before assignment
```
