### ISSUE TITLE
[Bug] List index out of range

### ISSUE THREAD

**Issue by modzilla99** [Footsiefat/zspotify#33]
When downloading the "Liked-Songs" at some point it will run into "list index out of range"

```
Traceback (most recent call last):
  File "zspotify.py", line 513, in <module>
    main()
  File "zspotify.py", line 509, in main
    client()
  File "zspotify.py", line 109, in client
    download_track(song['track']['id'], "Liked Songs/")
  File "zspotify.py", line 421, in download_track
    artists, album_name, name, image_url, release_year, disc_number, track_number, scraped_song_id, is_playable = get_song_info(
  File "zspotify.py", line 253, in get_song_info
    image_url = info['tracks'][0]['album']['images'][0]['url']
IndexError: list index out of range
```

Thanks for the script btw, it's great!

**Comment by Footsiefat** [comment]
This means it cant find the thumbnail url for that song and then decides to promptly crash because of that. Could you tell me the song name it trys to download right before the crash and if it shows up with a thumbnail in the normal spotify player?

**Comment by modzilla99** [comment]
```
###   APPLYING PATCH TO LET SONG DOWNLOAD   ###
###   FOUND SONG: Fall Out Boy - American BeautyAmerican Psycho    ###
###   DOWNLOADING RAW AUDIO   ###
###   CONVERTING TO MP3   ###
###   SETTING MUSIC TAGS   ###
###   SETTING THUMBNAIL   ###


Traceback (most recent call last):
  File "zspotify.py", line 513, in <module>
    main()
  File "zspotify.py", line 509, in main
    client()
  File "zspotify.py", line 109, in client
    download_track(song['track']['id'], "Liked Songs/")
  File "zspotify.py", line 421, in download_track
    artists, album_name, name, image_url, release_year, disc_number, track_number, scraped_song_id, is_playable = get_song_info(
  File "zspotify.py", line 253, in get_song_info
    image_url = info['tracks'][0]['album']['images'][0]['url']
IndexError: list index out of range
```
It's this one https://open.spotify.com/track/1ZwSPWyE7Sw9iQHTIwPjSF?si=0b927113fb854cc9 but I the thumbnail works properly on the player.

**Comment by Footsiefat** [comment]
errr it works fine for me haha

![image](https://user-images.githubusercontent.com/12180913/138061535-bf19d190-9f7e-4ff3-a2d3-7a9be9667f8c.png)

Can you please make sure you are using the newest version, and if that does'nt fix it...

Please add a line of code reading "print(info['tracks'][0])" just before the "image_url =" line of code at line 253 and paste what it outputs

**Comment by modzilla99** [comment]
Yeah I think I figured it out. It wasn't related to that song, it was the song after that. This one: https://api.spotify.com/v1/tracks/0xrKSHoblwiTpkKGSkFXnu

I just added a print before the download was supposed to happen:
```
###   SKIPPING: Breaking Benjamin - The Diary of Jane - Single Version (SONG ALREADY EXISTS)   ###


Invoking Download of:  {'album': {'album_type': 'album', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of'}, 'href': 'https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of', 'id': '0LyfQWJT6nXafLPZqxe9Of', 'name': '', 'type': 'artist', 'uri': 'spotify:artist:0LyfQWJT6nXafLPZqxe9Of'}], 'available_markets': [], 'external_urls': {'spotify': 'https://open.spotify.com/album/3A8fxryaB0G3YUUzJriMgA'}, 'href': 'https://api.spotify.com/v1/albums/3A8fxryaB0G3YUUzJriMgA', 'id': '3A8fxryaB0G3YUUzJriMgA', 'images': [], 'name': '', 'release_date': '2012-03-13', 'release_date_precision': 'day', 'total_tracks': 13, 'type': 'album', 'uri': 'spotify:album:3A8fxryaB0G3YUUzJriMgA'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of'}, 'href': 'https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of', 'id': '0LyfQWJT6nXafLPZqxe9Of', 'name': '', 'type': 'artist', 'uri': 'spotify:artist:0LyfQWJT6nXafLPZqxe9Of'}], 'available_markets': [], 'disc_number': 1, 'duration_ms': 214200, 'explicit': False, 'external_ids': {}, 'external_urls': {'spotify': 'https://open.spotify.com/track/0xrKSHoblwiTpkKGSkFXnu'}, 'href': 'https://api.spotify.com/v1/tracks/0xrKSHoblwiTpkKGSkFXnu', 'id': '0xrKSHoblwiTpkKGSkFXnu', 'is_local': False, 'name': '', 'popularity': 0, 'preview_url': None, 'track_number': 3, 'type': 'track', 'uri': 'spotify:track:0xrKSHoblwiTpkKGSkFXnu'}
Traceback (most recent call last):
  File "zspotify.py", line 514, in <module>
    main()
  File "zspotify.py", line 510, in main
    client()
  File "zspotify.py", line 110, in client
    download_track(song['track']['id'], "Liked Songs/")
  File "zspotify.py", line 422, in download_track
    artists, album_name, name, image_url, release_year, disc_number, track_number, scraped_song_id, is_playable = get_song_info(
  File "zspotify.py", line 254, in get_song_info
    image_url = info['tracks'][0]['album']['images'][0]['url']
IndexError: list index out of range
```
It is trying to download a song from "A broken Silence" that appears to have been removed. I guess we need to try and catch that. Then we could log it, instead of just stopping.
